name: CI

on:
  workflow_call:
    inputs:
      effective-branch:
        required: true
        type: string
      release:
        required: true
        type: boolean
      version:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        # only needed for release builds
        required: false
      AWS_SECRET_ACCESS_KEY:
        # only needed for release builds
        required: false
      DOCKER_USERNAME:
        # only needed for release builds
        required: false
      DOCKER_PASSWORD:
        # only needed for release builds
        required: false

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  integ-test:
    uses: ./.github/workflows/integ-test.yaml

  release:
    needs: [validate, integ-test]
    if: ${{ inputs.release || inputs.effective-branch == 'develop' }}
    uses: ./.github/workflows/release.yaml
    with:
      effective-branch: ${{ inputs.effective-branch }}
      release: ${{ inputs.release }}
      version: ${{ inputs.version }}
    secrets: inherit

  maven-publish:
    needs: [validate, integ-test]
    if: ${{ inputs.release }}
    uses: ./.github/workflows/maven-publish.yaml
    secrets: inherit

  distroless:
    needs: [validate, integ-test]
    if: ${{ inputs.release || inputs.effective-branch == 'develop' }}
    uses: ./.github/workflows/distroless.yaml
    with:
      effective-branch: ${{ inputs.effective-branch }}
      version: ${{ inputs.version }}
    secrets: inherit
