name: Cut release
on: [ workflow_dispatch ]

permissions:
  contents: write

jobs:
  cut-release:
    runs-on: ubuntu-latest
    outputs:
      effective-branch: ${{ steps.git-meta.outputs.EFFECTIVE_BRANCH }}
    env:
      SINCE_VERSION: "0.15.5"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure git
        run: |
          git config user.name "Imposter release bot"
          git config user.email "release-bot@imposter.sh"

      - name: Install since
        run: |
          cd "$( mktemp -d )"
          curl --fail -L -o since.tar.gz https://github.com/release-tools/since/releases/download/v${SINCE_VERSION}/since_${SINCE_VERSION}_linux_amd64.tar.gz
          tar xvf since.tar.gz
          cp since /usr/local/bin

      - name: Cut release
        run: since project release

      - name: Push changes
        run: git push origin main --tags

      - name: Determine effective branch
        id: git-meta
        run: |
          EFFECTIVE_BRANCH_NAME="$( ./scripts/get-effective-branch.sh )"
          echo "EFFECTIVE_BRANCH=${EFFECTIVE_BRANCH_NAME}" >> $GITHUB_OUTPUT

  ci:
    needs: [cut-release]
    uses: ./.github/workflows/ci.yaml
    with:
      effective-branch: ${{ needs.cut-release.outputs.effective-branch }}
      release: true
    secrets: inherit
