name: Cut release
on: [ workflow_dispatch ]

permissions:
  checks: write
  contents: write

jobs:
  cut-release:
    runs-on: ubuntu-latest
    env:
      SINCE_VERSION: "0.15.5"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure git
        run: |
          git config user.name "Imposter release bot"
          git config user.email "release-bot@imposter.sh"

      - name: Install since
        run: |
          cd "$( mktemp -d )"
          curl --fail -L -o since.tar.gz https://github.com/release-tools/since/releases/download/v${SINCE_VERSION}/since_${SINCE_VERSION}_linux_amd64.tar.gz
          tar xvf since.tar.gz
          cp since /usr/local/bin

      - name: Cut release
        run: since project release

      - name: Push changes
        run: git push origin main --tags

  ci:
    needs: [cut-release]
    uses: ./.github/workflows/ci.yaml
    with:
      effective-branch: main
      release: true
    secrets: inherit
