name: Pull Image from Docker Hub and Push to GitHub Container Registry

on:
  push:
    branches:
      - release

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image from Docker Hub
      run: docker pull outofcoffee/imposter:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag Docker image for GHCR
      run: docker tag outofcoffee/imposter:latest ghcr.io/${{ github.repository }}:latest

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository }}:latest