name: CI on push
on: [ push ]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      effective-branch: ${{ steps.git-meta.outputs.EFFECTIVE_BRANCH }}
      release: ${{ startsWith(github.ref, 'refs/tags/') }}
      version: ${{ steps.git-meta.outputs.CURRENT_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Determine effective branch
        id: git-meta
        run: |
          EFFECTIVE_BRANCH_NAME="$( ./scripts/get-effective-branch.sh )"
          echo "EFFECTIVE_BRANCH=${EFFECTIVE_BRANCH_NAME}" >> $GITHUB_OUTPUT
          CURRENT_VERSION="$( git describe --tags --exact-match )"
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

  ci:
    needs: [setup]
    uses: ./.github/workflows/ci.yaml
    with:
      effective-branch: ${{ needs.setup.outputs.effective-branch }}
      release: ${{ needs.setup.outputs.release == 'true' }}
      version: ${{ needs.setup.outputs.version }}
    secrets: inherit
